# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8ba16e7b0f7ffee14068e3fd536bd44fd00d226621200ba2b12e7a61d2a79f01d8f5beaa9df98c7568d5f8dc971936c3dd76eee9e18d53e03c527c57e8c59d9

test:
  secret_key_base: 62ded58f8765a06a4a538adbe56bf28ceb718e45805974e3135bb1d3de69f8711df651a46c02088945c9ee536d96d10e8f1196f36199855b1eb37b15b549d370

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
